/* 주요 카테고리 */
CREATE TABLE MAIN_CTGR (
	MAIN_CTGR_ID NUMBER NOT NULL, /* 주요 카테고리 ID */
	MAIN_CTGR_NAME VARCHAR2(100) /* 주요 카테고리 명 */
);

COMMENT ON TABLE MAIN_CTGR IS '주요 카테고리';

COMMENT ON COLUMN MAIN_CTGR.MAIN_CTGR_ID IS '주요 카테고리 ID';

COMMENT ON COLUMN MAIN_CTGR.MAIN_CTGR_NAME IS '주요 카테고리 명';

CREATE UNIQUE INDEX PK_MAIN_CTGR
	ON MAIN_CTGR (
		MAIN_CTGR_ID ASC
	);

ALTER TABLE MAIN_CTGR
	ADD
		CONSTRAINT PK_MAIN_CTGR
		PRIMARY KEY (
			MAIN_CTGR_ID
		);

/* 상품 대분류 */
CREATE TABLE LARGE_CTGR (
	LARGE_CTGR_ID NUMBER NOT NULL, /* 상품 대분류 ID */
	LARGE_CTGR_NAME VARCHAR2(100), /* 상품 대분류 명 */
	MAIN_CTGR_ID NUMBER /* 주요 카테고리 ID */
);

COMMENT ON TABLE LARGE_CTGR IS '상품 대분류';

COMMENT ON COLUMN LARGE_CTGR.LARGE_CTGR_ID IS '상품 대분류 ID';

COMMENT ON COLUMN LARGE_CTGR.MAIN_CTGR_NAME IS '상품 대분류 명';

COMMENT ON COLUMN LARGE_CTGR.MAIN_CTGR_ID IS '주요 카테고리 ID';

CREATE UNIQUE INDEX PK_LARGE_CTGR
	ON LARGE_CTGR (
		LARGE_CTGR_ID ASC
	);

ALTER TABLE LARGE_CTGR
	ADD
		CONSTRAINT PK_LARGE_CTGR
		PRIMARY KEY (
			LARGE_CTGR_ID
		);

/* 상품 중분류 */
CREATE TABLE MEDIUM_CTGR (
	MEDIUM_CTGR_ID NUMBER NOT NULL, /* 상품 중분류 ID */
	MEDIUM_CTGR_NAME VARCHAR2(100), /* 상품 중분류 명 */
	LARGE_CTGR_ID NUMBER /* 상품 대분류 ID */
);

COMMENT ON TABLE MEDIUM_CTGR IS '상품 중분류';

COMMENT ON COLUMN MEDIUM_CTGR.MEDIUM_CTGR_ID IS '상품 중분류 ID';

COMMENT ON COLUMN MEDIUM_CTGR.MEDIUM_CTGR_NAME IS '상품 중분류 명';

COMMENT ON COLUMN MEDIUM_CTGR.LARGE_CTGR_ID IS '상품 대분류 ID';

CREATE UNIQUE INDEX PK_MEDIUM_CTGR
	ON MEDIUM_CTGR (
		MEDIUM_CTGR_ID ASC
	);

ALTER TABLE MEDIUM_CTGR
	ADD
		CONSTRAINT PK_MEDIUM_CTGR
		PRIMARY KEY (
			MEDIUM_CTGR_ID
		);

/* 상품 소분류 */
CREATE TABLE SMALL_CTGR (
	SMALL_CTGR_ID NUMBER NOT NULL, /* 상품 소분류 ID */
	SMALL_CTGR_NAME VARCHAR2(100), /* 상품 소분류 명 */
	MEDIUM_CTGR_ID NUMBER /* 상품 중분류 ID */
);

COMMENT ON TABLE SMALL_CTGR IS '상품 소분류';

COMMENT ON COLUMN SMALL_CTGR.SMALL_CTGR_ID IS '상품 소분류 ID';

COMMENT ON COLUMN SMALL_CTGR.SMALL_CTGR_NAME IS '상품 소분류 명';

COMMENT ON COLUMN SMALL_CTGR.MEDIUM_CTGR_ID IS '상품 중분류 ID';

CREATE UNIQUE INDEX PK_SMALL_CTGR
	ON SMALL_CTGR (
		SMALL_CTGR_ID ASC
	);

ALTER TABLE SMALL_CTGR
	ADD
		CONSTRAINT PK_SMALL_CTGR
		PRIMARY KEY (
			SMALL_CTGR_ID
		);

ALTER TABLE LARGE_CTGR
	ADD
		CONSTRAINT FK_MAIN_CTGR_TO_LARGE_CTGR
		FOREIGN KEY (
			MAIN_CTGR_ID
		)
		REFERENCES MAIN_CTGR (
			MAIN_CTGR_ID
		);

ALTER TABLE MEDIUM_CTGR
	ADD
		CONSTRAINT FK_LARGE_CTGR_TO_MEDIUM_CTGR
		FOREIGN KEY (
			LARGE_CTGR_ID
		)
		REFERENCES LARGE_CTGR (
			LARGE_CTGR_ID
		);

ALTER TABLE SMALL_CTGR
	ADD
		CONSTRAINT FK_MEDIUM_CTGR_TO_SMALL_CTGR
		FOREIGN KEY (
			MEDIUM_CTGR_ID
		)
		REFERENCES MEDIUM_CTGR (
			MEDIUM_CTGR_ID
		);
        
 /* 상품 소분류 시퀀스 생성 */
 create sequence seq_SMALL_CTGR;
